### ISSUE TITLE
Error Messgae

### ISSUE THREAD

**Issue by Rando6400** [aGlitch/Mario-64-Randomizer#4]
![Error](https://user-images.githubusercontent.com/49498878/55920572-5984b680-5bc7-11e9-963f-bcde7dd6918d.PNG)
What does this mean? I've tried changing setups, but I keep getting this message. I tried ignoring it once, but my game crashed. I have basically everything checked off, what do I need to fix?

**Comment by TimeTravelPenguin** [comment]
There is probably an error is the business logic. The code is probably not generic enough, and thus doesn't cover the full range of possibilities. Can you replicate this? How did it occur?

**Comment by blu0191** [comment]
I managed to get the same exact error, it happened when I didn't use M64 extender on my rom. After doing so, it loaded the rom correctly. However, after loading a save file in the randomized rom I got this using PJ64 2.3.2.202 and a nightly build of 2.4.
![image](https://user-images.githubusercontent.com/12908954/56034977-e9754e00-5cf6-11e9-987e-49c757edd742.png)

**Comment by blu0191** [comment]
Update: I set the memory to 8 mb and now I don't get that error, but I do get stuck on this blank screen
![image](https://user-images.githubusercontent.com/12908954/56043637-a2de1e80-5d0b-11e9-897b-e07dbfbd8f16.png)

**Comment by blu0191** [comment]
This seems to also happen when I let Mario sleep in the title screen, must be something to do with the warps messing up.

**Comment by Rando6400** [comment]
![5egr55t6hu7i8hy6ht78i](https://user-images.githubusercontent.com/49498878/56462062-83d63100-638a-11e9-99a6-7ea115ec45b4.PNG)
Ok, the 1.1 update has introduced me to a new problem. What exactly am I supposed to do with the patch? I'm really confused

**Comment by Rando6400** [comment]
Ok, I managed to apply the patch. But now when I boot up the rom on an emulator, all it does it show the title screen with no sound, and then it crashes. I'm honestly at a total loss, now. What am I doing wrong?

**Comment by aGlitch** [comment]
@blupilot what rom / settings are you using?

@Rando6400 that patch is the same thing as extending the rom (8mb -> 64mb). Can you describe a bit more about your pj64 settings maybe? I'm not able to recreate your crash

**Comment by blu0191** [comment]
@aGlitch Oh actually I tried a later update that came out after I had that issue and everything went fine for some reason, idk why but it suddenly worked.
