### ISSUE TITLE
Cant seem to load file?

### ISSUE THREAD

**Issue by hax4dazy** [aGlitch/Mario-64-Randomizer#6]
Whenever i try to load a file i get "Error: 8mb Vanilla not supported. Do you want to download the Patch?" When i click yes it download's it but where do i put this? Is it like a add on or something.
I see no documents covering this happening anywhere. So is it just me?

**Comment by Dehaku** [comment]
Same situation, I even put the patch it downloaded into the patches folder of the randomizer program, but it still cannot load any of the mario roms I've found.

**Comment by hax4dazy** [comment]
Yeah i've put the file everywhere but the program still says that i have to download it....

**Comment by hax4dazy** [comment]
Ok so after some digging (thank god this is open saus) I came across this piece of code 
`                        MessageBox.Show("Your ROM was loaded!", "Done", MessageBoxButtons.OK, MessageBoxIcon.Asterisk);
                    }
                    else
                    {
                        DialogResult dialogResult = MessageBox.Show("Error: 8mb Vanilla not supported.\nDo you want to download the Patch?", "8mb Rom Detected", MessageBoxButtons.YesNo);
                        if (dialogResult == DialogResult.Yes)
                        {
                            System.Diagnostics.Process.Start("https://github.com/aGlitch/Mario-64-Randomizer/releases/download/1.0/Super.Mario.64.Random.bps");`


Now what is happening here is that the file is being loaded but when it doesnt load or something it just says "Error: 8mb Vanilla not supported." So i think something is or really wrong or something is going right and we are idiots

**Comment by TimeTravelPenguin** [comment]
To me, this looks like the kind of thing that happens when proper error handling isn't implemented.

The dev needs to really document his works with all the errors and things that could potentially happen, and then implementing correct error handling. Otherwise you get random errors like so where no one knows what the actual error is without manually digging through all the code every time there is a bug.

**Comment by hax4dazy** [comment]
Well the code doesn't mention a bps file anywhere else except from here. It seems like a random shitty error or something. I tried contacting him on discord but he doesn't have dm's enabled. Gonna try other versions to see if they work.

**Comment by hax4dazy** [comment]
Ok so randomly this week the program decided that it liked me and actually open'd the file. But right after that i saw that my m64 rom was corrupted in some way. So i had to repatch the rom. And then it gave me there error again. Idk what i did differently that time. Is it random?

**Comment by hax4dazy** [comment]
UPDATE: I have spoken to the dev and he said that we should use [this](https://www.romhacking.net/utilities/309/) tool to "apply" the patch. What the patch was supposed to be doing was extending the rom. But for some reason only he could open the patch and select his rom. So this is a good alternative.
